# Assignment For Numpy




Difficulty Level Beginner


# 1 Import the numpy package under the name np

In [21]:
import numpy as np

# Create a null vector of size 10

In [11]:
arr1 = np.zeros(10,dtype="int32")
arr1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# 1. Create a vector with values ranging from 10 to 49

In [13]:
arr2 = np.arange(10,50)
arr2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

# 1 Find the shape of previous array in question 3

In [15]:
np.shape(arr2)

(40,)

# 1 Print the type of the previous array in question 3

In [19]:
arr2.dtype

dtype('int32')

# 1 Print the numpy version and the configuration

In [27]:
# version
np.__version__


'1.18.5'

In [28]:

# config
np.show_config()

blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/DELL/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/DELL/Anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/DELL/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:

# 1 Print the dimension of the array in question 3

In [29]:
arr2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [32]:
arr2.ndim

1

# 1 .Create a boolean array with all the True values

In [40]:
b_arr = np.ones(10,"bool")
b_arr

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

# 1 .Create a two dimensional array

In [46]:
arr2d= np.arange(10).reshape(2,5)
arr2d

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

# or

In [47]:
arr2d = np.array([[0, 1, 2, 3, 4],[5, 6, 7, 8, 9]])
arr2d

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

# 1 .Create a three dimensional array

In [62]:
arr3d = np.arange(27).reshape(3,3,3)
arr3d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

# or

In [65]:
arr3d =  np.array([[[ 0,  1,  2],[ 3,  4,  5], [ 6,  7,  8]], [[ 9, 10, 11],[12, 13, 14],[15, 16, 17]], 
                   [[18, 19, 20], [21, 22, 23],[24, 25, 26]]])
arr3d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

# Difficulty Level Easy

# Reverse a vector (first element becomes last)

In [67]:
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
res_arr = arr1[::-1]
res_arr

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

# 1 .Create a null vector of size 10 but the fifth value which is 1

In [72]:
arr_null = np.zeros(10,"int")
arr_null[4]=1
arr_null

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

# 1.Create a 3x3 identity matrix

In [75]:
arr_id = np.identity(3,"int")
arr_id

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

# Convert the data type of the given array from int to float
# arr = np.array([1, 2, 3, 4, 5])

In [84]:
arr_int = np.array([1, 2, 3, 4, 5])
print("ARRAY INT TYPE:",arr_int)

arr_float = arr_int.astype('float')
print("ARRAY FLOAT TYPE:",arr_float)

ARRAY INT TYPE: [1 2 3 4 5]
ARRAY FLOAT TYPE: [1. 2. 3. 4. 5.]


# arr1 = np.array([[1., 2., 3.],

            

# [4., 5., 6.]])  


# arr2 = np.array([[0., 4., 1. [7., 2., 12.]])


# Multiply arr1 with arr2

In [5]:
import numpy as np
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]])
arr2 = np.array([[1., 2., 3.],[4., 5., 6.]])
mul = arr1 * arr2
print("Multiplicaton Of Array 1 and Array 2 is ",mul)

Multiplicaton Of Array 1 and Array 2 is  [[ 1.  4.  9.]
 [16. 25. 36.]]


# arr1 = np.array([[1., 2., 3.],[4., 5., 6.]]) 

# arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])

# Make an array by comparing both the arrays provided above

In [8]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]]) 

arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])

equal_arr = arr1 == arr2

equal_arr

array([[False, False, False],
       [False, False, False]])

# Extract all odd numbers from arr with values(0-9)

In [26]:
org_arr = np.arange(10)
odd_arr=a[a % 2 == 1]
print("Original Array :",org_arr)
print("Odd Number In Array :",odd_arr)

Original Array : [0 1 2 3 4 5 6 7 8 9]
Odd Number In Array : [1 3 5 7 9]


# Replace all odd numbers to -1 from previous array


In [27]:
org_arr[odd_arr]=-1
org_arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

# arr = np.arange(10)


# Replace the values of indexes 5,6,7 and 8 to 12

In [38]:
arr =np.arange(10)
print("Original Array :",arr)

numb_greater5 = arr[arr>=5]

arr[numb_greater5] =  numb_greater5 + 3

print("New Array After Added new Value :",arr)


Original Array : [0 1 2 3 4 5 6 7 8 9]
New Array After Added new Value : [ 0  1  2  3  4  8  9 10 11 12]


# Create a 2d array with 1 on the border and 0 inside

In [68]:
arr_1 = np.ones((3,3))
arr_1[1:-1,1:-1]=0
arr_1

array([[1., 1., 1.],
       [1., 0., 1.],
       [1., 1., 1.]])

In [67]:
arr_1 = np.ones((4,4))
arr_1[1:-1,1:-1]=0
arr_1

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

In [69]:
arr_1 = np.ones((5,5))
arr_1[1:-1,1:-1]=0
arr_1

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [70]:
arr_1 = np.ones((6,6))
arr_1[1:-1,1:-1]=0
arr_1

array([[1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1.]])

# Difficulty Level Medium

arr2d = np.array([[1, 2, 3],[4, 5, 6], [7, 8, 9]])


# Replace the value 5 to 12

In [78]:
arr2d = np.array([[1, 2, 3],[4, 5, 6], [7, 8, 9]])
arr2d[1,1]=12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

# arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])


# Convert all the values of 1st array to 64

In [84]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0]=64
arr3d

array([[[64, 64, 64],
        [64, 64, 64]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

# Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [88]:
arr2d = np.arange(10).reshape(2,5)
print("Orginal Array :",arr2d)
print("slice out the first 1st 1-D array from it :",arr2d[0])

Orginal Array : [[0 1 2 3 4]
 [5 6 7 8 9]]
slice out the first 1st 1-D array from it : [0 1 2 3 4]


# Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [89]:
print("slice out the 2nd value from 2nd 1-D array from it :",arr2d[1,1])


slice out the 2nd value from 2nd 1-D array from it : 6


# Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [90]:
arr2d

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [94]:
arr2d[0:2,3:4]

array([[3],
       [8]])

# Create a 10x10 array with random values and find the minimum and maximum values

In [107]:
arr2d=np.random.random((10,10))
print("10 BY 10 ARRAY \n",arr2d)
print("\nMIN VALUE ",arr2d.min())
print("Max Value VALUE ",arr2d.max())



10 BY 10 ARRAY 
 [[0.53711428 0.56965069 0.02214082 0.06125574 0.81139354 0.91031598
  0.83755315 0.8833142  0.00123975 0.62629558]
 [0.14395978 0.3107861  0.02274947 0.23319192 0.57959215 0.05970352
  0.68567209 0.8079599  0.86153918 0.2172059 ]
 [0.29572465 0.61596434 0.86105128 0.16109762 0.8624509  0.2088985
  0.26436324 0.43635382 0.59204463 0.28354691]
 [0.60979861 0.41317667 0.53817863 0.06823876 0.24481247 0.51860202
  0.64143101 0.76379531 0.13203364 0.98623008]
 [0.17103113 0.39395239 0.0312822  0.52638272 0.18164555 0.1575759
  0.35227184 0.60935965 0.09249836 0.92976134]
 [0.35475003 0.93919053 0.29632742 0.78962011 0.54157927 0.03358384
  0.85311763 0.68591167 0.71687864 0.97861879]
 [0.84822175 0.55926038 0.91427585 0.90177931 0.72340279 0.06616391
  0.38322598 0.39584169 0.76239608 0.03264453]
 [0.12205477 0.83662921 0.59620197 0.26929314 0.69912963 0.18535384
  0.5334419  0.44734256 0.10824019 0.84417863]
 [0.20625045 0.76204117 0.51893226 0.78174071 0.43752614 0.561754

# a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])

# Find the common items between a and b

In [113]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
c=np.intersect1d(a, b)
print("common items between a and b",c)

common items between a and b [2 4]


# a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])


# Find the positions where elements of a and b match

In [133]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
c = np.where(a==b)
c


(array([1, 3, 5, 7], dtype=int64),)

In [126]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
data[names !='Will']
data    

array([[ 1.36142359, -0.71592792,  0.65698956,  0.7837552 ],
       [ 0.15051856, -1.54658555,  1.02186918,  0.69242729],
       [ 0.89894916,  0.79636938,  0.44053321,  0.01259427],
       [ 0.49903245, -0.20899902, -1.45276061, -1.03073233],
       [-0.65296149,  0.69955268,  0.36403262, -0.9846939 ],
       [-0.07248189,  0.25968302,  0.18991161, -1.25888802],
       [ 1.69427602, -0.25656607,  1.6967684 ,  0.49536153]])

# Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [144]:
arr1 = np.arange(15.0).reshape(5,3)
print("Array :",arr1)
print("Type Of Array  :",arr1.dtype)


Array : [[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]
 [12. 13. 14.]]
Type Of Array  : float64


# Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [143]:
arr = np.arange(16.0).reshape(2,2,4)
print("Array :",arr)
print("Type Of Array  :",arr.dtype)


Array : [[[ 0.  1.  2.  3.]
  [ 4.  5.  6.  7.]]

 [[ 8.  9. 10. 11.]
  [12. 13. 14. 15.]]]
Type Of Array  : float64


# Swap axes of the array you created in Question 32


In [147]:
np.swapaxes(arr,0,1)

array([[[ 0.,  1.,  2.,  3.],
        [ 8.,  9., 10., 11.]],

       [[ 4.,  5.,  6.,  7.],
        [12., 13., 14., 15.]]])

In [148]:
np.swapaxes(arr,0,2)

array([[[ 0.,  8.],
        [ 4., 12.]],

       [[ 1.,  9.],
        [ 5., 13.]],

       [[ 2., 10.],
        [ 6., 14.]],

       [[ 3., 11.],
        [ 7., 15.]]])

# Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [177]:
arr = np.sqrt([1, 2, 3, 4, 5, 6,7,8,9,10]) 

print("original array", arr) 

arr[arr<=0.5] = 0

print("New resulting array: ", arr) 

original array [1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766]
New resulting array:  [1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766]
