# Numpy_Assignment_2:

# Question:1

Convert a 1D array to a 2D array with 2 rows?


In [3]:
import numpy as np
a=np.array([[0, 1, 2, 3, 4],[5, 6, 7, 8, 9]])
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

# Question:2
How to stack two arrays vertically?

In [5]:
a=np.array([[1,2,3],[4,5,6]])
np.vstack(a)

array([[1, 2, 3],
       [4, 5, 6]])

# Question:3
How to stack two arrays horizontally?

Desired Output:
array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1], [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [6]:
a=np.array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],[5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])
np.hstack(a)

array([0, 1, 2, 3, 4, 1, 1, 1, 1, 1, 5, 6, 7, 8, 9, 1, 1, 1, 1, 1])

# Question:4


How to convert an array of arrays into a flat 1d array?
Desired Output::
array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [7]:
a=np.array([[0,1,2,3,4,5,6,7,8,9],[10,11,12,13,14,15,16,17,18,19]])
print('\n',a,'\n')
print(a.ravel())
print(a.flatten())


 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]] 

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


# Question:5


How to Convert higher dimension into one dimension?

Desired Output:
array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])

In [8]:
a=np.array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])
a.reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

# Question:6


Convert one dimension to higher dimension?


In [9]:
a=np.array([[ 0, 1, 2],[ 3, 4, 5],[ 6, 7, 8],[ 9, 10, 11],[12, 13, 14]])
np.vstack(a)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

# Question:7


Create 5x5 an array and find the square of an array?

In [16]:
a=np.arange(25).reshape(5,5)
print(a,'\n')
print(np.square(a))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]] 

[[  0   1   4   9  16]
 [ 25  36  49  64  81]
 [100 121 144 169 196]
 [225 256 289 324 361]
 [400 441 484 529 576]]


# Question:8


Create 5x6 an array and find the mean?

In [20]:
a=np.arange(30).reshape(5,6)
print(a,'\n')
print(np.mean(a))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]] 

14.5


# Question:9


Find the standard deviation of the previous array in Q8?

In [21]:
np.std(a)

8.65544144839919

# Question:10
Find the median of the previous array in Q8?

In [22]:
np.median(a)

14.5

# Question:11
Find the transpose of the previous array in Q8?

In [25]:
print(a)
np.transpose(a)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

# Question:12
Create a 4x4 an array and find the sum of diagonal elements?

In [26]:
a=np.arange(16).reshape(4,4)
print(a)
print('Sum =',np.trace(a))


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Sum = 30


# Question:13
Find the determinant of the previous array in Q12?

In [28]:
print(np.linalg.det(a))
print(np.linalg.det([[1,2],[3,4]]))

-2.9582283945787796e-30
-2.0000000000000004


# Question:14
Find the 5th and 95th percentile of an array?

In [30]:
print(a)
print('\n',np.percentile(a,5))
print(np.percentile(a,95))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

 0.75
14.25


# Question:15
How to find if a given array has any null values?

In [31]:
print(a)
print('\n',np.isnan(a))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

 [[False False False False]
 [False False False False]
 [False False False False]
 [False False False False]]
